### ISSUE TITLE
broken urls in SSL settings review

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/launchdock-connect#5]
![zingville___dashboard_connect](https://cloud.githubusercontent.com/assets/439959/12341287/616c7040-bad5-11e5-8b96-4c1b5ce7ef95.png)

**Comment by jshimko** [comment]
Fixed with commit https://github.com/reactioncommerce/launchdock-connect/commit/c4d9208d2aa3e165354a65ad8e20e2d09ca8fefd
