### ISSUE TITLE
subscribed messaging Account Status

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/launchdock-connect#7]
![zingville___dashboard_connect](https://cloud.githubusercontent.com/assets/439959/12341334/c3e88812-bad5-11e5-9047-2c4dc1e5f58a.png)

**Comment by jshimko** [comment]
Done.  https://github.com/reactioncommerce/launchdock-connect/commit/cb215341b895136d9b3496d0e140f350903c7537

Now shows free trial state or the chosen subscription and next payment date.
