### ISSUE TITLE
add monthly / yearly options to account status

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/launchdock-connect#8]
![zingbabies___dashboard_connect_and_clipboard_history_and_reactioncommerce_reaction](https://cloud.githubusercontent.com/assets/439959/12341611/c699c3ee-bad7-11e5-8b18-56697b003368.png)

@saralouhicks needs copy

**Comment by jshimko** [comment]
Done.  Subscription chooser UI added here: https://github.com/reactioncommerce/launchdock-connect/commit/cb215341b895136d9b3496d0e140f350903c7537
